In [1]:
import glob
import pandas as pd
import numpy as np

def dfwData():
    
    All_GFW_Grid = pd.DataFrame()
    for year in range(2012, 2019):

        yearby = glob.glob('Fishing_By_Vessel/' + str(year) + "\*.csv")

        li = []
        for yr in yearby:
            df = pd.read_csv(yr, index_col=None, header=0)
            li.append(df)

        GFW_Year = pd.concat(li, axis=0, ignore_index=True)
        All_GFW_Grid = pd.concat([All_GFW_Grid, GFW_Year])

    All_GFW_Grid.lat_bin = All_GFW_Grid.lat_bin/10
    All_GFW_Grid.lon_bin = All_GFW_Grid.lon_bin/10
    
    return All_GFW_Grid
    
All_GFW_Grid = dfwData()

All_GFW_Grid.head

<bound method NDFrame.head of                              date  lat_bin  lon_bin       mmsi  fishing_hours
0         2012-01-01 00:00:00 UTC    -46.1    -60.7  416755000       2.457917
1         2012-01-01 00:00:00 UTC    -46.1    -60.7  440548000       2.400417
2         2012-01-01 00:00:00 UTC    -46.0    -60.7  440548000       1.614444
3         2012-01-01 00:00:00 UTC    -46.0    -60.7  416032500      11.497083
4         2012-01-01 00:00:00 UTC    -45.9    -60.7  416842000      11.521944
5         2012-01-01 00:00:00 UTC    -45.9    -60.6  416046800       4.023194
6         2012-01-01 00:00:00 UTC    -45.8    -60.7  441303000       0.783194
7         2012-01-01 00:00:00 UTC    -45.8    -60.6  441303000       3.201528
8         2012-01-01 00:00:00 UTC    -45.8    -60.6  440502000       2.402361
9         2012-01-01 00:00:00 UTC    -45.7    -60.7  441412000       4.037917
10        2012-01-01 00:00:00 UTC    -45.5    -60.1  441495000       2.433056
11        2012-01-01 00:00:00 UTC    -45.4    -60.6  440818000       4.017361
12        2012-01-01 00:00:00 UTC      7.3    -31.3  431316000       0.015278
13        2012-01-01 00:00:00 UTC    -16.0   -121.4  431182000       3.316667
14        2012-01-01 00:00:00 UTC    -15.8   -121.4  431182000       0.875139
15        2012-01-01 00:00:00 UTC    -15.7   -121.4  431182000       0.116389
16        2012-01-01 00:00:00 UTC    -15.4   -121.4  431182000       3.127778
17        2012-01-01 00:00:00 UTC    -15.3   -121.5  431182000       6.638611
18        2012-01-01 00:00:00 UTC     -4.3   -174.0  440108000       0.960833
19        2012-01-01 00:00:00 UTC     -4.2   -174.0  440108000       1.780556
20        2012-01-01 00:00:00 UTC     -4.1    178.5  538060017      12.167917
21        2012-01-01 00:00:00 UTC     -4.0   -160.1  440617000       0.840000
22        2012-01-01 00:00:00 UTC     -4.0   -160.0  440617000       1.049444
23        2012-01-01 00:00:00 UTC     -3.9    178.6  538060017       4.797361
24        2012-01-01 00:00:00 UTC     -3.2    162.7  440886000       6.675972
25        2012-01-01 00:00:00 UTC     -3.2    163.0  440886000      12.198333
26        2012-01-01 00:00:00 UTC     -3.1    162.6  440886000       2.654583
27        2012-01-01 00:00:00 UTC     -2.9    162.6  440886000       4.553889
28        2012-01-01 00:00:00 UTC     -1.4    178.0  440772000       4.969028
29        2012-01-01 00:00:00 UTC     -1.1    178.3  440772000      10.569444
...                           ...      ...      ...        ...            ...
17935386  2018-12-31 00:00:00 UTC    -51.3    -68.6  701006427       3.576806
17935387  2018-12-31 00:00:00 UTC    -51.3     69.5  635212000       1.051667
17935388  2018-12-31 00:00:00 UTC    -51.3     69.6  635212000       0.062222
17935389  2018-12-31 00:00:00 UTC    -25.7    112.1  503024660       0.808333
17935390  2018-12-31 00:00:00 UTC    -25.7    112.0  503024660       0.987917
17935391  2018-12-31 00:00:00 UTC    -25.7     34.0  275454000       0.050833
17935392  2018-12-31 00:00:00 UTC    -25.7     57.3  225374000       0.305417
17935393  2018-12-31 00:00:00 UTC    -25.7     57.5  225374000       0.747361
17935394  2018-12-31 00:00:00 UTC    -25.7     57.6  225374000       0.381806
17935395  2018-12-31 00:00:00 UTC    -25.7     13.6  659036000       1.819306
17935396  2018-12-31 00:00:00 UTC    -25.7     42.2  431200750       0.537361
17935397  2018-12-31 00:00:00 UTC    -25.7     42.4  431200750       0.875833
17935398  2018-12-31 00:00:00 UTC    -25.7    112.2  503501300       1.793056
17935399  2018-12-31 00:00:00 UTC     -0.1    162.5  416002568       0.333333
17935400  2018-12-31 00:00:00 UTC     -0.1    162.6  416002568       0.333194
17935401  2018-12-31 00:00:00 UTC     -0.1    162.7  416002568       1.830833
17935402  2018-12-31 00:00:00 UTC     -0.1     81.1  417341252       1.921111
17935403  2018-12-31 00:00:00 UTC     -0.1    158.8  416076700       1.089444
17935404  2018-12-31 00:00:00 UTC     -0.1    158.7  416076700       0.076667
17935405  2018-12-31 00:00:00 UTC     -0.1    167.0  553111750       0.480556
17935406  2018-12-31 00:00:00 UTC     -0.1    167.1  553111750       3.490417
17935407  2018-12-31 00:00:00 UTC     -0.1   -165.7  412205520       1.552639
17935408  2018-12-31 00:00:00 UTC     -0.1   -165.6  412205520       0.333194
17935409  2018-12-31 00:00:00 UTC     -0.1   -165.1  412205520       1.525278
17935410  2018-12-31 00:00:00 UTC     -0.1   -122.1  200041700       1.178333
17935411  2018-12-31 00:00:00 UTC     -0.1   -122.3  200041700       0.883056
17935412  2018-12-31 00:00:00 UTC     -0.1   -122.4  200041700       0.765694
17935413  2018-12-31 00:00:00 UTC     -0.1    161.2  416003814       3.092222
17935414  2018-12-31 00:00:00 UTC     -0.1    161.1  416003814       2.174167
17935415  2018-12-31 00:00:00 UTC     -0.1   -120.2  412440045       1.661111

[74697925 rows x 5 columns]>

In [7]:
All_Animals_Oceanreach = pd.read_csv('Oceanreach/All_Animal_Data.csv')
All_Animals_Oceanreach

,active,datetime,id,latitude,longitude,tz_datetime,animal_type,animal_id,epoch_time
0,1,2012-03-16 18:31:39,1,-34.14200,22.20000,16 March 2012 6:31:39 PM +0900,White Shark (Carcharodon carcharias),9,1331922699
1,1,2012-03-16 18:48:58,2,-34.11500,22.20100,16 March 2012 6:48:58 PM +0900,White Shark (Carcharodon carcharias),9,1331923738
2,1,2012-03-16 20:15:40,3,-34.13800,22.20000,16 March 2012 8:15:40 PM +0900,White Shark (Carcharodon carcharias),9,1331928940
3,1,2012-03-16 23:09:05,4,-34.19200,22.22800,16 March 2012 11:09:05 PM +0900,White Shark (Carcharodon carcharias),9,1331939345
4,1,2012-03-17 0:36:43,5,-34.20400,22.23900,17 March 2012 12:36:43 AM +0900,White Shark (Carcharodon carcharias),9,1331944603
5,1,2012-03-17 0:52:50,6,-34.21000,22.20900,17 March 2012 12:52:50 AM +0900,White Shark (Carcharodon carcharias),9,1331945570
6,1,2012-03-17 1:16:51,7,-34.21800,22.20800,17 March 2012 1:16:51 AM +0900,White Shark (Carcharodon carcharias),9,1331947011
7,1,2012-03-17 2:36:14,8,-34.23600,22.20400,17 March 2012 2:36:14 AM +0900,White Shark (Carcharodon carcharias),9,1331951774
8,1,2012-03-17 4:32:38,9,-34.22400,22.18700,17 March 2012 4:32:38 AM +0900,White Shark (Carcharodon carcharias),9,1331958758
9,1,2012-03-17 4:33:52,10,-34.24600,22.20800,17 March 2012 4:33:52 AM +0900,White Shark (Carcharodon carcharias),9,1331958832
10,1,2012-03-17 5:20:21,11,-34.27300,22.15400,17 March 2012 5:20:21 AM +0900,White Shark (Carcharodon carcharias),9,1331961621
11,1,2012-03-17 5:49:14,12,-34.26600,22.20900,17 March 2012 5:49:14 AM +0900,White Shark (Carcharodon carcharias),9,1331963354
12,1,2012-03-17 6:11:17,13,-34.26900,22.19900,17 March 2012 6:11:17 AM +0900,White Shark (Carcharodon carcharias),9,1331964677
13,1,2012-03-17 7:02:45,14,-34.33500,22.20300,17 March 2012 7:02:45 AM +0900,White Shark (Carcharodon carcharias),9,1331967765
14,1,2012-03-17 7:31:57,15,-34.35000,22.18200,17 March 2012 7:31:57 AM +0900,White Shark (Carcharodon carcharias),9,1331969517
15,1,2012-03-18 2:23:05,16,-34.37000,21.87100,18 March 2012 2:23:05 AM +0900,White Shark (Carcharodon carcharias),9,1332037385
16,1,2012-03-18 2:30:24,17,-34.36900,21.87000,18 March 2012 2:30:24 AM +0900,White Shark (Carcharodon carcharias),9,1332037824
17,1,2012-03-18 5:12:16,19,-34.95300,22.08200,18 March 2012 5:12:16 AM +0900,White Shark (Carcharodon carcharias),9,1332047536
18,1,2012-03-18 5:32:18,20,-34.42600,21.88800,18 March 2012 5:32:18 AM +0900,White Shark (Carcharodon carcharias),9,1332048738
19,1,2012-03-18 6:41:50,21,-34.41000,21.78400,18 March 2012 6:41:50 AM +0900,White Shark (Carcharodon carcharias),9,1332052910
20,1,2012-03-18 7:08:53,22,-34.40900,21.78600,18 March 2012 7:08:53 AM +0900,White Shark (Carcharodon carcharias),9,1332054533
21,1,2012-03-18 7:22:12,23,-34.41400,21.79100,18 March 2012 7:22:12 AM +0900,White Shark (Carcharodon carcharias),9,1332055332
22,1,2012-03-18 14:26:26,24,-34.44600,21.84400,18 March 2012 2:26:26 PM +0900,White Shark (Carcharodon carcharias),9,1332080786
23,1,2012-03-18 14:45:14,25,-34.38000,21.57500,18 March 2012 2:45:14 PM +0900,White Shark (Carcharodon carcharias),9,1332081914
24,1,2012-03-18 14:45:29,26,-34.38500,21.62300,18 March 2012 2:45:29 PM +0900,White Shark (Carcharodon carcharias),9,1332081929
25,1,2012-03-18 19:12:07,27,-34.40300,21.44000,18 March 2012 7:12:07 PM +0900,White Shark (Carcharodon carcharias),9,1332097927
26,1,2012-03-18 19:25:01,28,-34.40200,21.44100,18 March 2012 7:25:01 PM +0900,White Shark (Carcharodon carcharias),9,1332098701
27,1,2012-03-19 0:12:28,30,-34.44300,21.42100,19 March 2012 12:12:28 AM +0900,White Shark (Carcharodon carcharias),9,1332115948
28,1,2012-03-19 0:30:51,31,-34.44700,21.39900,19 March 2012 12:30:51 AM +0900,White Shark (Carcharodon carcharias),9,1332117051
29,1,2012-03-19 2:04:23,32,-34.47300,21.39200,19 March 2012 2:04:23 AM +0900,White Shark (Carcharodon carcharias),9,1332122663
...,...,...,...,...,...,...,...,...,...
76002,1,2019-02-18 17:39:05,83582,43.98454,14.68849,18 February 2019 5:39:05 PM +0900,Loggerhead Sea Turtle (Caretta caretta),299,1550511545
76003,1,2019-02-18 17:41:16,83583,36.74325,12.38728,18 February 2019 5:41:16 PM +0900,Loggerhead Sea Turtle (Caretta caretta),301,1550511676
76004,1,2019-02-18 18:06:48,83584,33.27219,11.81885,18 February 2019 6:06:48 PM +0900,Loggerhead Sea Turtle (Caretta caretta),295,1550513208
76005,1,2019-02-18 20:38:18,83585,37.05045,-74.88224,18 February 2019 8:38:18 PM +0900,Mako Shark (Isurus oxyrinchus),273,1550522298
76006,1,2019-02-18 19:25:35,83586,33.27690,11.80431,18 February 2019 7:25:35 PM +0900,Loggerhead Sea Turtle (Caretta caretta),295,1550517935
76007,1,2019-02-18 22:15:10,83587,37.04226,-74.70307,18 February 2019 10:15:10 PM +0900,Mako Shark (Isurus oxyrinchus),273,1550528110
76008,1,2019-02-18 22:49:44,83588,29.41920,-80.81381,18 February 2019 10:49:44 PM +0900,White Shark (Carcharodon carcharias),326,1550530184
76009,1,2019-02-18 23:10:29,83589,37.05092,-74.68675,18 February 2019 11:10:29 PM +0900,Mako Shark (Isurus oxyrinchus),273,1550531429
76010,1,2019-02-18 23:10:59,83590,29.41422,-80.81569,18 February 2019 11:10:59 PM +0900,White Shark (Carcharodon carcharias),326,1550531459
76011,1,2019-02-18 23:19:48,83591,37.05239,-74.68401,18 February 2019 11:19:48 PM +0900,Mako Shark (Isurus oxyrinchus),273,1550531988
76012,1,2019-02-19 0:57:13,83592,28.44636,-91.59169,19 February 2019 12:57:13 AM +0900,Mako Shark (Isurus oxyrinchus),239,1550537833
76013,1,2019-02-19 1:06:20,83593,29.33661,-80.82543,19 February 2019 1:06:20 AM +0900,White Shark (Carcharodon carcharias),326,1550538380
76014,1,2019-02-19 0:02:01,83594,24.51530,-82.60322,19 February 2019 12:02:01 AM +0900,White Shark (Carcharodon carcharias),310,1550534521
76015,1,2019-02-19 2:15:12,83595,-20.10617,148.79290,19 February 2019 2:15:12 AM +0900,Hammerhead Shark (Sphyrna),325,1550542512
76016,1,2019-02-19 7:17:06,83596,37.17510,-74.55135,19 February 2019 7:17:06 AM +0900,Mako Shark (Isurus oxyrinchus),273,1550560626
76017,1,2019-02-19 8:13:13,83597,27.57497,-96.29908,19 February 2019 8:13:13 AM +0900,Mako Shark (Isurus oxyrinchus),286,1550563993
76018,1,2019-02-19 10:11:47,83598,37.20815,-74.59087,19 February 2019 10:11:47 AM +0900,Mako Shark (Isurus oxyrinchus),273,1550571107
76019,1,2019-02-19 10:31:34,83599,37.22745,-74.60334,19 February 2019 10:31:34 AM +0900,Mako Shark (Isurus oxyrinchus),273,1550572294
76020,1,2019-02-19 10:31:34,83600,37.22745,-74.60334,19 February 2019 10:31:34 AM +0900,Mako Shark (Isurus oxyrinchus),273,1550572294
76021,1,2019-02-19 10:36:45,83601,37.22550,-74.61829,19 February 2019 10:36:45 AM +0900,Mako Shark (Isurus oxyrinchus),273,1550572605
76022,1,2019-02-19 11:14:07,83602,37.23686,-74.59650,19 February 2019 11:14:07 AM +0900,Mako Shark (Isurus oxyrinchus),273,1550574847
76023,1,2019-02-19 12:11:49,83603,36.21289,12.20337,19 February 2019 12:11:49 PM +0900,Loggerhead Sea Turtle (Caretta caretta),300,1550578309
76024,1,2019-02-19 12:11:27,83604,36.72830,12.60714,19 February 2019 12:11:27 PM +0900,Loggerhead Sea Turtle (Caretta caretta),301,1550578287
76025,1,2019-02-19 14:49:09,83605,-9.50672,154.55485,19 February 2019 2:49:09 PM +0900,Whale Shark (Rhincodon Typus),316,1550587749
76026,1,2019-02-19 15:33:22,83607,36.25591,12.17025,19 February 2019 3:33:22 PM +0900,Loggerhead Sea Turtle (Caretta caretta),300,1550590402
76027,1,2019-02-19 15:02:07,83608,36.23761,12.19801,19 February 2019 3:02:07 PM +0900,Loggerhead Sea Turtle (Caretta caretta),300,1550588527
76028,1,2019-02-19 15:04:53,83609,36.72358,12.68536,19 February 2019 3:04:53 PM +0900,Loggerhead Sea Turtle (Caretta caretta),301,1550588693
76029,1,2019-02-19 15:52:11,83610,-20.12298,148.79121,19 February 2019 3:52:11 PM +0900,Hammerhead Shark (Sphyrna),325,1550591531
76030,1,2019-02-19 17:26:41,83613,-16.41919,145.69141,19 February 2019 5:26:41 PM +0900,Tiger Shark (Galeocerdo cuvier),319,1550597201
76031,1,2019-02-19 17:52:06,83614,33.28588,11.78236,19 February 2019 5:52:06 PM +0900,Loggerhead Sea Turtle (Caretta caretta),295,1550598726

In [9]:
lats_gfw = All_GFW_Grid.lat_bin
lons_gfw = All_GFW_Grid.lon_bin
lats_or = All_Animals_Oceanreach.latitude
lons_or =All_Animals_Oceanreach.longitude
 
max_lat = 60
min_lat = -60
max_lon = -180
min_lon = 180

In [ ]:
sns.set_style("white")
plt.figure(figsize=(20,20)) 

m = Basemap(llcrnrlon=min_lon, llcrnrlat=min_lat,
            urcrnrlon=max_lon, urcrnrlat=max_lat, projection='mill', resolution ='l')

m.drawmapboundary()
m.fillcontinents("#cccccc",lake_color="#cccccc")
parallels = np.arange(min_lat,max_lat,20.)
m.drawparallels(parallels,labels=[1,0,0,0],fontsize=18,color='#cccccc')
meridians = np.arange(min_lon,max_lon,20.)
m.drawmeridians(meridians,labels=[0,0,0,1],fontsize=18,color='#cccccc')

m.drawmapboundary(fill_color='#A2C3FF')
m.drawcountries()
x,y= m(lons_gfw, lats_gfw)
size = 3
m.plot(x,y,marker = 'o',markersize=size,markeredgecolor = 'none',
       alpha = 1,linestyle='None', label="Satellite")

x,y= m(lons_or, lats_or)
size = 3
m.plot(x,y,marker = 'o',markersize=size,markeredgecolor = 'none',
       alpha = 1,linestyle='None', label="Terrestrial", color = "red")


plt.title("All Vessels", 
         fontsize=29)
plt.legend(fontsize=24)
plt.show()